packages:
  - "package"
  - "docs"

allowBuilds:
  core-js: false
  esbuild: true
  sharp: true
  simple-git-hooks: true
  workerd: true

minimumReleaseAgeExclude:
  - starlight-theme-flexoki
  - astro-emit-asset@0.1.4
