import { describe, expect, it, vi } from "vitest";

const { emitAsset } = vi.hoisted(() => ({ emitAsset: vi.fn() }));
vi.mock("astro-emit-asset/emit", () => ({ emitAsset }));

const { emitLilypondAsset } = await import("./emitLilypondAsset.js");

const REAL_SVG =
	'<svg xmlns="http://www.w3.org/2000/svg" width="105" height="55" viewBox="0 0 105 55">content</svg>';

const BASE = {
	title: "score",
	format: "svg" as const,
	source: "...",
	resolution: 144,
	crop: true,
	sizeScale: 1,
	binaryPath: "lilypond",
};

/** Runs the real `generateAsset` thunk passed to the mocked `emitAsset`, like `astro-emit-asset` would on a cache miss. */
async function resolveGenerated() {
	const generateAsset = emitAsset.mock.calls.at(-1)?.[2];
	return await generateAsset();
}

describe("emitLilypondAsset", () => {
	it("calls emitAsset with '<title>.[hash].<format>' as the path (name before hash) and render deps, including sizeScale, as the cache key", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.abc123.svg", meta: {} },
		]);

		await emitLilypondAsset({
			...BASE,
			title: "bach-bwv610",
			source: "\\relative c' { c d e }",
			render: vi.fn().mockResolvedValue([Buffer.from(REAL_SVG)]),
		});

		expect(emitAsset).toHaveBeenCalledWith(
			"bach-bwv610.[hash].svg",
			["\\relative c' { c d e }", "svg", 144, true, 1],
			expect.any(Function),
		);
	});

	it("busts the cache when sizeScale changes, even with identical source/format/resolution/crop", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.abc123.svg", meta: {} },
		]);
		const render = vi.fn().mockResolvedValue([Buffer.from(REAL_SVG)]);

		await emitLilypondAsset({ ...BASE, sizeScale: 1, render });
		await emitLilypondAsset({ ...BASE, sizeScale: 2, render });

		const [, firstKey] = emitAsset.mock.calls[0];
		const [, secondKey] = emitAsset.mock.calls[1];
		expect(firstKey).not.toEqual(secondKey);
	});

	it("returns one page per emitted asset, in order", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.0.abc123.svg", meta: { width: 1, height: 2 } },
			{ src: "/_astro/score.1.abc123.svg", meta: { width: 3, height: 4 } },
		]);

		const pages = await emitLilypondAsset({
			...BASE,
			crop: false,
			render: vi.fn().mockResolvedValue([Buffer.from("a"), Buffer.from("b")]),
		});

		expect(pages).toEqual([
			{ src: "/_astro/score.0.abc123.svg", width: 1, height: 2 },
			{ src: "/_astro/score.1.abc123.svg", width: 3, height: 4 },
		]);
	});

	it("passes generateAsset an array of pages regardless of page count", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.abc123.svg", meta: {} },
		]);
		const render = vi.fn().mockResolvedValue([Buffer.from(REAL_SVG)]);

		await emitLilypondAsset({ ...BASE, render });

		const generated = await resolveGenerated();
		expect(Array.isArray(generated)).toBe(true);
		expect(generated).toEqual([
			{ data: Buffer.from(REAL_SVG), meta: { width: 105, height: 55 } },
		]);
	});

	it("multiplies dimensions by sizeScale without touching the generated bytes", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.abc123.svg", meta: {} },
		]);
		const render = vi.fn().mockResolvedValue([Buffer.from(REAL_SVG)]);

		await emitLilypondAsset({ ...BASE, sizeScale: 1.5, render });

		const [generated] = await resolveGenerated();
		expect(generated.data).toEqual(Buffer.from(REAL_SVG));
		expect(generated.meta).toEqual({ width: 157.5, height: 82.5 });
	});

	it("leaves width/height undefined when dimensions can't be read from the bytes", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.abc123.svg", meta: {} },
		]);
		const render = vi.fn().mockResolvedValue([Buffer.from("not an svg")]);

		await emitLilypondAsset({ ...BASE, render });

		const [generated] = await resolveGenerated();
		expect(generated.meta).toEqual({ width: undefined, height: undefined });
	});

	it("throws a clear, actionable error instead of calling emitAsset when binaryPath is unset", async () => {
		emitAsset.mockClear();

		await expect(
			emitLilypondAsset({
				...BASE,
				binaryPath: undefined,
				render: vi.fn(),
			}),
		).rejects.toThrow(/lilypond\(\).*Astro config/s);
		expect(emitAsset).not.toHaveBeenCalled();
	});
});
