import { describe, expect, it, vi } from "vitest";

const { emitAsset } = vi.hoisted(() => ({ emitAsset: vi.fn() }));
vi.mock("astro-emit-asset/emit", () => ({ emitAsset }));

const { emitLilypondAsset } = await import("./emitLilypondAsset.js");

const REAL_SVG =
	'<svg xmlns="http://www.w3.org/2000/svg" width="105" height="55" viewBox="0 0 105 55">content</svg>';

/** Runs the real `generateAsset` thunk passed to the mocked `emitAsset`, like `astro-emit-asset` would on a cache miss. */
async function resolveGenerated() {
	const generateAsset = emitAsset.mock.calls.at(-1)?.[2];
	return await generateAsset();
}

describe("emitLilypondAsset", () => {
	it("calls emitAsset with '<title>.<format>' as the path and render deps as the cache key", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.abc123.svg", meta: {} },
		]);

		await emitLilypondAsset({
			title: "bach-bwv610",
			format: "svg",
			source: "\\relative c' { c d e }",
			resolution: 144,
			crop: true,
			sizeScale: 1,
			render: vi.fn().mockResolvedValue([Buffer.from(REAL_SVG)]),
		});

		expect(emitAsset).toHaveBeenCalledWith(
			"bach-bwv610.svg",
			["\\relative c' { c d e }", "svg", 144, true],
			expect.any(Function),
		);
	});

	it("returns one page per emitted asset, in order", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.0.abc123.svg", meta: { width: 1, height: 2 } },
			{ src: "/_astro/score.1.abc123.svg", meta: { width: 3, height: 4 } },
		]);

		const pages = await emitLilypondAsset({
			title: "score",
			format: "svg",
			source: "...",
			resolution: 144,
			crop: false,
			sizeScale: 1,
			render: vi.fn().mockResolvedValue([Buffer.from("a"), Buffer.from("b")]),
		});

		expect(pages).toEqual([
			{ src: "/_astro/score.0.abc123.svg", width: 1, height: 2 },
			{ src: "/_astro/score.1.abc123.svg", width: 3, height: 4 },
		]);
	});

	it("passes generated bytes and dimensions read from those bytes through to emitAsset", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.abc123.svg", meta: {} },
		]);
		const render = vi.fn().mockResolvedValue([Buffer.from(REAL_SVG)]);

		await emitLilypondAsset({
			title: "score",
			format: "svg",
			source: "...",
			resolution: 144,
			crop: true,
			sizeScale: 1,
			render,
		});

		expect(await resolveGenerated()).toEqual([
			{ data: Buffer.from(REAL_SVG), meta: { width: 105, height: 55 } },
		]);
	});

	it("multiplies dimensions by sizeScale without touching the generated bytes", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.abc123.svg", meta: {} },
		]);
		const render = vi.fn().mockResolvedValue([Buffer.from(REAL_SVG)]);

		await emitLilypondAsset({
			title: "score",
			format: "svg",
			source: "...",
			resolution: 144,
			crop: true,
			sizeScale: 1.5,
			render,
		});

		const [generated] = await resolveGenerated();
		expect(generated.data).toEqual(Buffer.from(REAL_SVG));
		expect(generated.meta).toEqual({ width: 157.5, height: 82.5 });
	});

	it("leaves width/height undefined when dimensions can't be read from the bytes", async () => {
		emitAsset.mockResolvedValue([
			{ src: "/_astro/score.abc123.svg", meta: {} },
		]);
		const render = vi.fn().mockResolvedValue([Buffer.from("not an svg")]);

		await emitLilypondAsset({
			title: "score",
			format: "svg",
			source: "...",
			resolution: 144,
			crop: true,
			sizeScale: 1,
			render,
		});

		const [generated] = await resolveGenerated();
		expect(generated.meta).toEqual({ width: undefined, height: undefined });
	});
});
